server:
    port: 8080
    session:
      cookie:
        name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: i388601-pocketbyku
      clientSecret: Dso0D0HmpeBZkTyQ4727HBVP7rzEz41pddrrj8K1
      accessTokenUri: https://identity.fhict.nl/connect/token
      userAuthorizationUri: https://identity.fhict.nl/connect/authorize
      redirectUri: http://localhost:8080
      scope: fhict fhict_personal
    resource:
      userInfoUri: https://api.fhict.nl/people/me
spring:
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true